import "./globals.css";
import { Nunito } from "next/font/google";
import UserCheck from "./components/UserChecking";
import Navbar from "./components/Navbar";
const font = Nunito({
  weight: ["400", "700"],
  subsets: ["latin"],
});
export const metadata = {
  title: "DripWear",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased bg-neutral-950 text-white flex flex-col`}
      >
        <UserCheck />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
